### ISSUE TITLE
Add Graph Algorithms

### ISSUE THREAD

**Issue by Nzarite** [Nzarite/cp#1]
put some c++ files that have graph algoithms like Kruskal, Floyd-Warshall etc. with apt description

**Comment by darkl1ght** [comment]
I would like to contribute to this.

**Comment by Nzarite** [comment]
> I would like to contribute to this.

@darkl1ght I have assigned you this issue.
If you have any doubts regarding, you may ask here.

**Comment by darkl1ght** [comment]
#2 has been raised.

**Comment by Nzarite** [comment]
okay so I am closing this issue.
